language: python
jobs:
  include:
    - name: Py3.6 (and doc deploy)
      python: 3.6
      env:
        - DEPLOY_DIR=$PWD/deploy
        - ROOT_DOC_DIR=$PWD/doc/global
        - C_DOC_DIR=$PWD/c_models/html
        - PY_DOC_DIR=$PWD/doc/source/_build/html
    - name: Py3.7
      python: 3.7
    - name: Py3.8
      python: 3.8
    - name: Py2.7 (legacy)
      python: 2.7
dist: focal

env:
  # Need this environment if we're doing tests without a config file
  - READTHEDOCS=True

cache: pip

addons:
  apt:
    packages:
      - vera++
      - libxml2-utils
      - gcc-arm-none-eabi
      - libnewlib-arm-none-eabi

before_install:
  # Work around ludicrous Travis bug
  - git clone https://github.com/SpiNNakerManchester/SupportScripts.git support
  - python support/travis_blocking_stdout.py
  # Bring pip up to date
  - pip install --upgrade pip setuptools wheel
  - pip install --only-binary=numpy,scipy numpy scipy
  # SpiNNakerManchester internal dependencies; development mode
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNUtils.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMachine.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNMan.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/PACMAN.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/DataSpecification.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/spalloc.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker.git
  - support/pipinstall.sh git://github.com/SpiNNakerManchester/sPyNNaker8.git
  # C dependencies
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinnaker_tools.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/spinn_common.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/SpiNNFrontEndCommon.git
  - support/gitclone.sh https://github.com/SpiNNakerManchester/sPyNNaker.git
  - export SPINN_DIRS=$PWD/spinnaker_tools
  - export NEURAL_MODELLING_DIRS=$PWD/sPyNNaker/neural_modelling
  
install:
  - pip install -r requirements-test.txt
  - pip install python-coveralls
  - python ./setup.py install

before_script:
  # Initialise builds against spinnaker_tools
  - make -C $SPINN_DIRS
  - make -C spinn_common install
  - make -C SpiNNFrontEndCommon/c_common install
  # Make a test config
  - echo '[Machine]' > ~/.spiNNakerGraphFrontEnd.cfg
  - echo "machineName = $SPINNAKER_BOARD_ADDRESS" >> ~/.spiNNakerGraphFrontEnd.cfg
  - echo "version = ${SPINNAKER_BOARD_VERSION:-5}" >> ~/.spiNNakerGraphFrontEnd.cfg
  - echo '[Database]' >> ~/.spiNNakerGraphFrontEnd.cfg
  - echo '[Simulation]' >> ~/.spiNNakerGraphFrontEnd.cfg
  - echo '[Buffers]' >> ~/.spiNNakerGraphFrontEnd.cfg

script:
  # Tests
  # - py.test unittests --cov spinnaker_graph_front_end
  # Code quality check
  - flake8 spinn_gym
  - flake8 examples
  # C
  - make -C c_code
  - support/run-vera.sh c_code
  # Documentation build check
  #- cd doc/source
  #- sphinx-build -T -E -b html -d _build/doctrees-readthedocsdirhtml -D language=en . _build/html
  #- sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
  #- sphinx-build -T -b singlehtml -d _build/doctrees-readthedocssinglehtmllocalmedia -D language=en . _build/localmedia

after_success:
  - cd $TRAVIS_BUILD_DIR
  - coveralls
